# Generated by Django 5.2 on 2026-02-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_cart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
