# Generated by Django 5.2 on 2025-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_fruits"),
    ]

    operations = [
        migrations.AddField(
            model_name="fruits",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vegetables",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
