# Generated by Django 5.2 on 2025-06-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_fruits_quantity_vegetables_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Best_seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("filled_star", models.ImageField(upload_to="")),
                ("unfilled_star", models.ImageField(upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="Fruit_images/")),
            ],
        ),
    ]
