# Generated by Django 5.2 on 2026-02-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
